"""Persistence for gitkit reports — `~/.luxe/reports/<repo_hash>/`.

Mirrors the `~/.luxe/sessions` / `~/.luxe/compares` convention so reports
survive temp-clone cleanup and accrete into a per-repo audit trail.
"""

from __future__ import annotations

import re
import shutil
import time
import uuid
from pathlib import Path

from luxe.ephemeral import is_ephemeral
from luxe.gitkit import patterns
from luxe.paths import luxe_home
from luxe.memory.project import repo_hash


def reports_dir(repo_path: str | Path) -> Path:
    """Return the report directory for a repo (`~/.luxe/reports/<repo_hash>/`)."""
    return luxe_home() / "reports" / repo_hash(repo_path)


def save_report(repo_path: str | Path, kind: str, text: str,
                meta: dict | None = None) -> Path | None:
    """Write a gitkit report to disk and return its path.

    Args:
        repo_path: the analyzed repo (used to derive the report directory).
        kind: report kind — gitaudit | gitchange.
        text: the model's markdown report body.
        meta: optional header fields (model, head, repo display path, etc.).

    Returns:
        Path to `~/.luxe/reports/<repo_hash>/<kind>-<timestamp>-<rand>.md`. The
        short random suffix avoids clashes between same-second / concurrent runs.

    Side effects: creates the report directory (parents, exist_ok) and writes
    one markdown file with a YAML frontmatter header.
    """
    meta = dict(meta or {})
    ts = int(time.time())
    if is_ephemeral():
        # Ephemeral: the report is returned and rendered, just never filed.
        return None
    out_dir = reports_dir(repo_path)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{kind}-{ts}-{uuid.uuid4().hex[:6]}.md"

    header = {
        "kind": kind,
        "repo": str(meta.get("repo", repo_path)),
        "timestamp": ts,
        "model": meta.get("model", ""),
        "head": meta.get("head", ""),
    }
    # Optional pass-through keys (deep-mode marker + timing telemetry). Allowlisted
    # rather than splatting `meta` so the frontmatter schema stays explicit and
    # callers can't accidentally pollute it. `mode`/`chunks` were passed by deep
    # mode but silently dropped before this; they now land in the header too.
    for k in ("mode", "chunks", "total_wall_s", "n_passes", "avg_pass_s",
              "base", "merge_base"):
        if k in meta:
            header[k] = meta[k]
    front = "\n".join(f"{k}: {v}" for k, v in header.items())
    path.write_text(f"---\n{front}\n---\n\n{text.rstrip()}\n")
    return path


def _frontmatter_head(text: str) -> str:
    """Pull the `head:` value out of a report's YAML frontmatter ('' if absent)."""
    if not text.startswith("---\n"):
        return ""
    end = text.find("\n---", 4)
    for line in (text[4:end] if end != -1 else "").splitlines():
        if line.startswith("head:"):
            return line.split(":", 1)[1].strip()
    return ""


def latest_report_for(repo_path: str | Path, kind: str, head: str) -> str | None:
    """Return the body (post-frontmatter) of the newest saved `<kind>` report for
    `repo_path` whose frontmatter HEAD matches `head`, or None. Used so gitchange
    can consume a prior same-commit gitaudit (head-equality keeps the contract
    clean — a stale audit never bleeds into a different commit's change plan)."""
    d = reports_dir(repo_path)
    if not d.is_dir():
        return None
    cands = sorted(d.glob(f"{kind}-*.md"), key=lambda p: p.stat().st_mtime,
                   reverse=True)
    for p in cands:
        try:
            text = p.read_text()
        except OSError:
            continue
        if head and _frontmatter_head(text) == head:
            return text.split("\n---\n", 1)[-1].strip()
    return None


_MIRROR_FILES = ("survey_notes.md", "chunks.json", "mapped.json", "head")
_MIRROR_README = (
    "# .luxe/gitkit — generated by `luxe gitkit`\n\n"
    "Survey map + the latest gitaudit/gitchange report for this repo, mirrored "
    "here so they travel with the code (commit them or not, your call). **Safe to "
    "delete or add to `.gitignore`** — the canonical copy lives under "
    "`~/.luxe/reports/`. Regenerated on each `luxe gitaudit`/`gitchange` run; "
    "skip with `--no-mirror`.\n")


def mirror_to_repo(repo_path: str | Path, kind: str, report_text: str,
                   head: str) -> Path | None:
    """Mirror the canonical map + the just-saved report into a committable
    `<repo>/.luxe/gitkit/` (default-on; `~/.luxe/reports/` stays canonical). This
    is an ORCHESTRATOR write (plain Python, never an agent tool) and touches only
    the `.luxe/gitkit/` sidecar — never source — mirroring the `.luxe/memory.md`
    precedent. Best-effort: any OS error is swallowed and returns None so a stray
    filesystem failure never aborts the analysis."""
    if is_ephemeral():
        # This is the site that literally creates `<repo>/.luxe/` — the exact
        # thing --ephemeral promises not to do.
        return None
    try:
        dest = Path(repo_path) / ".luxe" / "gitkit"
        dest.mkdir(parents=True, exist_ok=True)
        src_map = reports_dir(repo_path) / "map"
        for name in _MIRROR_FILES:
            f = src_map / name
            if f.is_file():
                shutil.copy2(f, dest / name)
        reports = dest / "reports"
        reports.mkdir(exist_ok=True)
        (reports / f"{kind}-{head or 'nohead'}.md").write_text(
            report_text.rstrip() + "\n")
        # gitchange: also mirror the machine-readable plan so the apply-ready artifact
        # travels with the repo (only gitchange writes plan-<head>.json).
        plan_json = reports_dir(repo_path) / f"plan-{head or 'nohead'}.json"
        if plan_json.is_file():
            plans = dest / "plans"
            plans.mkdir(exist_ok=True)
            shutil.copy2(plan_json, plans / plan_json.name)
        (dest / "README.md").write_text(_MIRROR_README)
        return dest
    except OSError:
        return None


# a finding item line: "- **high** ..." / "1. **Critical:** ..." (inline severity)
_INLINE_SEV_RE = re.compile(
    r"^\s*(?:[-*]|\d+[.)])\s+\*\*\s*(critical|high|medium|low)\b", re.IGNORECASE)
_ITEM_RE = re.compile(r"^\s*(?:[-*]|\d+[.)])\s+\S")


def _walk_sections(report_md: str):
    """Yield (line, active severity section | None, is_severity_header) for
    every line of a report. A severity section opens at a severity heading at
    any of levels 2-4 (`## High`, `### High` under `## Bugs & security`, the
    per-finding `### M — title`) and closes at the next heading at the same
    or a shallower level; deeper non-severity headings stay inside it.
    Headings inside fenced code are code, not structure. The section value is
    `(level, severity, per_finding)`."""
    section: tuple[int, str, bool] | None = None
    in_fence = False
    for ln in (report_md or "").splitlines():
        if patterns.is_fence(ln):
            in_fence = not in_fence
            yield ln, section, False
            continue
        level = 0 if in_fence else patterns.heading_level(ln)
        if level:
            sh = patterns.severity_header(ln)
            if sh is not None:
                section = sh
                yield ln, section, True
                continue
            if section is not None and level <= section[0]:
                section = None
        yield ln, section, False


_BOLD_LEAD_RE = re.compile(r"^\*\*(.+?)\*\*")


def _count_group_findings(lines: list[str]) -> int:
    """Findings under one hidden GROUP header (`### Low`): its bold-lead
    finding paragraphs (`**3. title**`, `**`a.py:3` — title**` — but not a
    `**Impact:**` field label) when the model wrote that shape, else its
    top-level list items — never the evidence/impact lines under a finding."""
    bold = 0
    for ln in lines:
        m = _BOLD_LEAD_RE.match(ln)
        if m and not m.group(1).rstrip().endswith(":"):
            bold += 1
    if bold:
        return bold
    return sum(1 for ln in lines if _ITEM_RE.match(ln) and not ln[:1].isspace())


def filter_min_severity(report_md: str, min_severity: str) -> tuple[str, int]:
    """DISPLAY-side severity filter (the saved report is always the full,
    unfiltered text — never silently cap coverage). Drops severity sections
    below the threshold (a per-finding heading counts as one finding; a group
    heading counts its findings, `_count_group_findings`) and individual
    `- **sev**`-shaped finding lines below it elsewhere. Returns (filtered
    markdown, number of findings filtered out)."""
    thr = patterns.SEVERITY_RANK.get((min_severity or "").lower(), 0)
    if thr <= 1:                       # low = show everything
        return report_md, 0
    out: list[str] = []
    dropped = 0
    hidden_group: list[str] | None = None
    for ln, section, is_hdr in _walk_sections(report_md):
        if is_hdr or section is None:
            if hidden_group is not None:
                dropped += _count_group_findings(hidden_group)
                hidden_group = None
        if section is not None and patterns.SEVERITY_RANK[section[1]] < thr:
            if is_hdr:
                if section[2]:
                    dropped += 1           # the heading IS the finding
                else:
                    hidden_group = []
            elif hidden_group is not None:
                hidden_group.append(ln)
            continue
        m = _INLINE_SEV_RE.match(ln)
        if m and patterns.SEVERITY_RANK.get(m.group(1).lower(), 5) < thr:
            dropped += 1
            continue
        out.append(ln)
    if hidden_group is not None:
        dropped += _count_group_findings(hidden_group)
    return "\n".join(out), dropped


def extract_findings(report_md: str) -> str:
    """Slice ONLY the findings out of a gitaudit report — every severity
    section (`## High`, `### High`, `### M — title`; heading → end of that
    section) plus inline `- **sev** …` finding lines found elsewhere (the
    deterministic deep render's `## Additional findings`); drop the repository
    summary / `## Area:` prose / structural notes. Keeps the injected payload
    small when a prior audit is fed to gitchange. '' if no findings."""
    if not report_md:
        return ""
    out: list[str] = []
    for ln, section, _is_hdr in _walk_sections(report_md):
        if section is not None or _INLINE_SEV_RE.match(ln):
            out.append(ln)
    return "\n".join(out).strip()
