"""Persistence for gitkit reports — `~/.luxe/reports/<repo_hash>/`.

Mirrors the `~/.luxe/sessions` / `~/.luxe/compares` convention so reports
survive temp-clone cleanup and accrete into a per-repo audit trail.
"""

from __future__ import annotations

import re
import shutil
import time
import uuid
from pathlib import Path

from luxe.memory.project import repo_hash


def reports_dir(repo_path: str | Path) -> Path:
    """Return the report directory for a repo (`~/.luxe/reports/<repo_hash>/`)."""
    return Path.home() / ".luxe" / "reports" / repo_hash(repo_path)


def save_report(repo_path: str | Path, kind: str, text: str,
                meta: dict | None = None) -> Path:
    """Write a gitkit report to disk and return its path.

    Args:
        repo_path: the analyzed repo (used to derive the report directory).
        kind: report kind — gitsummary | gitreview | gitrefactor.
        text: the model's markdown report body.
        meta: optional header fields (model, head, repo display path, etc.).

    Returns:
        Path to `~/.luxe/reports/<repo_hash>/<kind>-<timestamp>-<rand>.md`. The
        short random suffix avoids clashes between same-second / concurrent runs.

    Side effects: creates the report directory (parents, exist_ok) and writes
    one markdown file with a YAML frontmatter header.
    """
    meta = dict(meta or {})
    ts = int(time.time())
    out_dir = reports_dir(repo_path)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{kind}-{ts}-{uuid.uuid4().hex[:6]}.md"

    header = {
        "kind": kind,
        "repo": str(meta.get("repo", repo_path)),
        "timestamp": ts,
        "model": meta.get("model", ""),
        "head": meta.get("head", ""),
    }
    # Optional pass-through keys (deep-mode marker + timing telemetry). Allowlisted
    # rather than splatting `meta` so the frontmatter schema stays explicit and
    # callers can't accidentally pollute it. `mode`/`chunks` were passed by deep
    # mode but silently dropped before this; they now land in the header too.
    for k in ("mode", "chunks", "total_wall_s", "n_passes", "avg_pass_s"):
        if k in meta:
            header[k] = meta[k]
    front = "\n".join(f"{k}: {v}" for k, v in header.items())
    path.write_text(f"---\n{front}\n---\n\n{text.rstrip()}\n")
    return path


def _frontmatter_head(text: str) -> str:
    """Pull the `head:` value out of a report's YAML frontmatter ('' if absent)."""
    if not text.startswith("---\n"):
        return ""
    end = text.find("\n---", 4)
    for line in (text[4:end] if end != -1 else "").splitlines():
        if line.startswith("head:"):
            return line.split(":", 1)[1].strip()
    return ""


def latest_report_for(repo_path: str | Path, kind: str, head: str) -> str | None:
    """Return the body (post-frontmatter) of the newest saved `<kind>` report for
    `repo_path` whose frontmatter HEAD matches `head`, or None. Used so gitrefactor
    can consume a prior same-commit gitreview (head-equality keeps the contract
    clean — a stale review never bleeds into a different commit's refactor)."""
    d = reports_dir(repo_path)
    if not d.is_dir():
        return None
    cands = sorted(d.glob(f"{kind}-*.md"), key=lambda p: p.stat().st_mtime,
                   reverse=True)
    for p in cands:
        try:
            text = p.read_text()
        except OSError:
            continue
        if head and _frontmatter_head(text) == head:
            return text.split("\n---\n", 1)[-1].strip()
    return None


_MIRROR_FILES = ("survey_notes.md", "chunks.json", "mapped.json", "head")
_MIRROR_README = (
    "# .luxe/gitkit — generated by `luxe gitkit`\n\n"
    "Survey map + the latest gitreview/gitrefactor report for this repo, mirrored "
    "here so they travel with the code (commit them or not, your call). **Safe to "
    "delete or add to `.gitignore`** — the canonical copy lives under "
    "`~/.luxe/reports/`. Regenerated on each `luxe gitreview`/`gitrefactor` run; "
    "skip with `--no-mirror`.\n")


def mirror_to_repo(repo_path: str | Path, kind: str, report_text: str,
                   head: str) -> Path | None:
    """Mirror the canonical map + the just-saved report into a committable
    `<repo>/.luxe/gitkit/` (default-on; `~/.luxe/reports/` stays canonical). This
    is an ORCHESTRATOR write (plain Python, never an agent tool) and touches only
    the `.luxe/gitkit/` sidecar — never source — mirroring the `.luxe/memory.md`
    precedent. Best-effort: any OS error is swallowed and returns None so a stray
    filesystem failure never aborts the analysis."""
    try:
        dest = Path(repo_path) / ".luxe" / "gitkit"
        dest.mkdir(parents=True, exist_ok=True)
        src_map = reports_dir(repo_path) / "map"
        for name in _MIRROR_FILES:
            f = src_map / name
            if f.is_file():
                shutil.copy2(f, dest / name)
        reports = dest / "reports"
        reports.mkdir(exist_ok=True)
        (reports / f"{kind}-{head or 'nohead'}.md").write_text(
            report_text.rstrip() + "\n")
        # gitplan: also mirror the machine-readable plan so the apply-ready artifact
        # travels with the repo (only gitplan writes plan-<head>.json).
        plan_json = reports_dir(repo_path) / f"plan-{head or 'nohead'}.json"
        if plan_json.is_file():
            plans = dest / "plans"
            plans.mkdir(exist_ok=True)
            shutil.copy2(plan_json, plans / plan_json.name)
        (dest / "README.md").write_text(_MIRROR_README)
        return dest
    except OSError:
        return None


_SEV_HDR_RE = re.compile(r"^##\s*(Critical|High|Medium|Low)\b", re.IGNORECASE)


def extract_findings(report_md: str) -> str:
    """Slice ONLY the severity-grouped findings out of a gitreview report — keep each
    `## Critical|High|Medium|Low` block (header → next `##`), drop the repository
    summary / `## Area:` notes / files-checked prose. Keeps the injected payload
    small when a prior review is fed to gitrefactor. '' if no findings sections."""
    if not report_md:
        return ""
    out: list[str] = []
    keep = False
    for ln in report_md.splitlines():
        if ln.startswith("## "):
            keep = bool(_SEV_HDR_RE.match(ln))
        if keep:
            out.append(ln)
    return "\n".join(out).strip()
